name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - run: sudo apt update && sudo apt install python3-pip && sudo pip3 install PyInstaller && cd src && sudo pyi-makespec main.py && cd ..
      
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: my-exe
        path: src/dist/windows # or path/to/artifact

